[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  # Helps with Next.js 15 compatibility
  NEXT_USE_NETLIFY_EDGE = "true"

# Environment variables for the Notion API
[build.environment.production]
  NOTION_API_KEY = "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"
  NOTION_DATABASE_ID = "1cac2c53a70a8033b8bdf2b914caf25a"

# Handle routes for SPA behavior
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server/index"
  status = 200 